### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by digitalwm** [xk/JASON#5]
Exception thrown when trying to parse the data that was serialized:

SyntaxError: Unexpected token :
    at Object.parse (/node_modules/JASON/index.js:270:21)
    at Object.<anonymous> (/distribPlugin.js:30:37)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

I serialized and got the following

{"var5":true,"var2":[],"var1":0,"var3":(function (v) {
        this.var1 = v;
    }),"var4":Date}

Regards,
Dan.

**Comment by digitalwm** [comment]
to fix this, 

replace this:

exports.parse = function(t) {
        return eval(t);
}

with this:

exports.parse = function(t) {
        return eval('(' + t + ')');
}

**Comment by digitalwm** [comment]
It's really something strange :D. If I use simple object what I specify works, If I use objects with cyclic properties and complex ones, it doesn't because the generated string contains "(" and ")";

**Comment by digitalwm** [comment]
``` javascript
exports.stringify = function(o) {
        var retString = "";
        seen= [];
        paths= [];
        cyclic= [];
        ademas= [];

        var r= strfy(o, 'o');
        if (cyclic.length || ademas.length) {
            retString = '(function(o){\n  ';
            retString += cyclic.join(';\n  ');
            if(cyclic.length > 0) {
                retString += ';\n  ';
            };
            retString += ademas.join(';\n  ');
            if(ademas.length > 0) {
                retString += ';\n  ';
            }
            retString += 'return o;\n})('+ r+ ');';
            return retString;
        }
        else {
            return '('+ r+ ')';
        }
    }
```

This should fix the above problem and other one that ; were added on some corner cases. Also ignore my above suggestion. :)

**Comment by bjouhier** [comment]
Looks similar to issue #2 which was fixed on Feb 4 by adding parentheses in the eval. Also, Jorge made one more change to parse since then (added `eval` wrapped into a `new Function(...)`). So it may already be solved.

Can you try with the latest code and post the code that breaks it if it still does.

**Comment by digitalwm** [comment]
Hi, Just got the latest code and it works. Can someone update the version on NPM repository? Thanks

**Comment by bjouhier** [comment]
Done. Version 0.1.2 is published to NPM.
